applications:
  atuin:
    type: 'rust:1'

    web:
      commands:
        start: /app/target/release/atuin server start

      locations:
        /:
          allow: false
          passthru: true

    relationships:
      db: "pgsql:postgresql"

    hooks:
      build: |
        set -e
        export CARGO_HOME=$PLATFORM_CACHE_DIR/rust/cargo
        export RUSTUP_HOME=$PLATFORM_CACHE_DIR/rust
        export CARGO_TARGET_DIR=$PLATFORM_CACHE_DIR/target
        cargo build --release --all
        echo "Deploy"
        mkdir -p $HOME/target/release/
        cp `find $CARGO_TARGET_DIR/release/* -maxdepth 0 -type f -print` $HOME/target/release/
        df -h $PLATFORM_CACHE_DIR
        # clean the build cache if utilization is over 80%
        if [ `df --output=pcent $PLATFORM_CACHE_DIR | tail -1|cut -d% -f1` -gt 80 ] ; then cargo clean ; fi

services:
  pgsql:
    type: postgresql:16
