applications:
    app:
        type: "php:7.4"

        dependencies:
            php:
                wp-cli/wp-cli-bundle: "^2.4"
                psy/psysh: "^0.10.4"

        relationships:
            database: "db:mysql"

        variables:
            php:
                session.gc_maxlifetime: '200000'
                session.cookie_lifetime: '2000000'
                pcre.backtrack_limit: '200000'
                pcre.recursion_limit: '200000'

        web:
            locations:
                "/":
                    # The public directory of the app, relative to its root.
                    root: "public_html"
                    # The front-controller script to send non-static requests to.
                    passthru: "/index.php"
                    # Wordpress has multiple roots (wp-admin) so the following is required
                    index:
                        - "index.php"
                    # The number of seconds whitelisted (static) content should be cached.
                    expires: 600
                    scripts: true
                    allow: true
                    rules:
                        ^/composer\.json:
                            allow: false
                        ^/license\.txt$:
                            allow: false
                        ^/readme\.html$:
                            allow: false
                "/wp-content/cache":
                    root: "public_html/wp-content/cache"
                    scripts: false
                    allow: false
                "/wp-content/uploads":
                    root: "public_html/wp-content/uploads"
                    scripts: false
                    allow: false
                    rules:
                        # Allow access to common static files.
                        '(?<!\-lock)\.(?i:jpe?g|gif|png|svg|bmp|ico|css|js(?:on)?|eot|ttf|woff|woff2|pdf|docx?|xlsx?|pp[st]x?|psd|odt|key|mp[2-5g]|m4[av]|og[gv]|wav|mov|wm[av]|avi|3g[p2])$':
                            allow: true
                            expires: 1w

        mounts:
            "public_html/wp-content/cache":
                source: storage
                source_path: "cache"
            "public_html/wp-content/uploads":
                source: storage
                source_path: "uploads"

        hooks:
            deploy: |
                wp --path=/app/public_html/ cache flush
                wp --path=/app/public_html/ core update-db
                wp --path=/app/public_html/ cron event run --due-now

        source:
            operations:
                auto-update:
                    command: |
                        # get our pub directory as defined in the application
                        pubDir=$(echo $PLATFORM_APPLICATION | base64 --decode | jq -r '.web.locations."/".root')
                        # grab the latest version of WordPress, save locally based on pubDir name
                        curl https://wordpress.org/latest -o "${PLATFORM_CACHE_DIR}/${pubDir}.tar.gz"
                        cd "${PLATFORM_CACHE_DIR}"
                        tar -xvf "${pubDir}.tar.gz" && rm "${pubDir}.tar.gz"
                        # the archive always expands into a "wordpress" directory
                        rsync -av wordpress/ "${PLATFORM_SOURCE_DIR}/${pubDir}"
                        cd "${PLATFORM_SOURCE_DIR}"
                        git add --all
                        confirm=$(git status --porcelain=1);
                        if [ -z "${confirm}" ]; then
                            echo "No changes to commit."
                        else
                            git commit -m "Auto updated via source operations" 
                        fi

services:
    db:
        type: mariadb:11.2

    # memcached:
    #     type: memcached:1.6

routes:
    "https://{default}/":
        type: upstream
        upstream: "app:http"
        cache:
            enabled: true
            # Base the cache on the session cookies. Ignore all other cookies.
            cookies:
                - '/^wordpress_logged_in_/'
                - '/^wordpress_sec_/'
                - 'wordpress_test_cookie'
                - '/^wp-settings-/'
                - '/^wp-postpass/'
                - '/^wp-resetpass-/'

    "https://www.{default}/":
        type: redirect
        to: "https://{default}/"
